name: AIRunningCoach
options:
  bundleIdPrefix: com.zhouxiaohong
  deploymentTarget:
    iOS: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    DEVELOPMENT_TEAM: PW83W8JG6H
    SWIFT_VERSION: "5"
    CLANG_ENABLE_MODULES: YES

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift
    from: "2.0.0"

targets:
  AIRunningCoach:
    type: application
    platform: iOS
    sources:
      - AIRunningCoachApp.swift
      - Views
      - Managers
      - Models
      - Utils
      - Assets.xcassets
      - AIRunningCoach-Bridging-Header.h
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.zhouxiaohong.AIRunningCoach
        PRODUCT_NAME: AIRunningCoach
        INFOPLIST_KEY_CFBundleDisplayName: "AI跑步教练"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: AIRunningCoach.entitlements
        ENABLE_PREVIEWS: YES
        GENERATE_INFOPLIST_FILE: YES
        SWIFT_OBJC_BRIDGING_HEADER: AIRunningCoach-Bridging-Header.h
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UIBackgroundModes: location
        INFOPLIST_KEY_NSLocationWhenInUseUsageDescription: "需要访问您的位置信息来记录跑步轨迹和计算距离"
        INFOPLIST_KEY_NSLocationAlwaysAndWhenInUseUsageDescription: "需要访问您的位置信息来记录跑步轨迹和计算距离，即使应用在后台运行"
        LD_RUNPATH_SEARCH_PATHS:
          - "$(inherited)"
          - "@executable_path/Frameworks"
      configs:
        Debug:
          SWIFT_OPTIMIZATION_LEVEL: "-Onone"
          SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG $(inherited)"
        Release:
          SWIFT_COMPILATION_MODE: wholemodule
    dependencies:
      - package: Supabase
    entitlements:
      path: AIRunningCoach.entitlements
